[build-system]
requires = ["uv_build>=0.9.22,<0.10.0"]
build-backend = "uv_build"

[project]
name = "mlops_mnist"
version = "0.0.1"
description = "MLOPS applications on MNIST"
authors = [
  { name = "yerenkl", email = "yerenkl@gmail.com" },
]

keywords = ["machine learning", "MLOps"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.115.6",
    "torch==2.6.0",
    "typer==0.15.1",
    "uvicorn==0.34.0",
    "numpy==2.4.1",
    "matplotlib==3.10.8",
    "scikit-learn==1.8.0",
    "tqdm==4.67.1",
    "dvc>=3.66.1",
    "dvc-gdrive>=3.0.1",
    "wandb>=0.23.1",
    "torchvision>=0.21.0",
    "pytorch-lightning>=2.6.0",
]

[dependency-groups]
dev = [
    "coverage==7.6.9",
    "invoke==2.2.0",
    "pre-commit==4.1.0",
    "pytest==8.3.4",
    "ruff>=0.8.0",
    "mypy==1.19.1",
    "mkdocs-material==9.7.1",
    "mkdocstrings-python==2.0.1",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[tool.ruff]
lint.select = ["I"]
line-length=120

[tool.coverage.run]
omit = ["tests/*"]

[project.scripts]
train = "mlops_mnist.train:app"
evaluate = "mlops_mnist.evaluate:app"
