name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # Continue running all jobs even if one fails
      fail-fast: false 
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.12]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        cache: true

    - name: Install dependencies
      run: |
        uv sync --dev --locked

    - name: Test with pytest
      run: |
        uv run pytest -v